# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_start', models.CharField(default=0, max_length=100)),
                ('id_end', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=150, unique=True)),
                ('sourceid', models.CharField(default='', max_length=20, null=True)),
                ('ojname', models.CharField(default='', max_length=30)),
                ('time_limit', models.CharField(max_length=20, null=True)),
                ('memory_limit', models.CharField(max_length=20, null=True)),
                ('title', models.TextField(default='', max_length=200)),
                ('description', models.TextField(max_length=100000, null=True)),
                ('pinput', models.TextField(max_length=100000, null=True)),
                ('poutput', models.TextField(max_length=100000, null=True)),
                ('sample_input', models.TextField(max_length=100000, null=True)),
                ('sample_output', models.TextField(max_length=100000, null=True)),
                ('hint', models.TextField(max_length=100000, null=True)),
                ('source', models.TextField(max_length=200, null=True)),
                ('ac_rate', models.CharField(max_length=10, null=True)),
                ('user_ac_rate', models.CharField(max_length=10, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('knowledge_tree_node_id', models.IntegerField(default='-1')),
                ('knowledge_tree_node_name', models.CharField(default='未分类', max_length=30)),
                ('hot_degree', models.FloatField(max_length=20, null=True)),
                ('difficult', models.FloatField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ojname', models.CharField(default='', max_length=30)),
                ('hot_average_sub', models.FloatField(default=0, max_length=20)),
                ('hot_average_sqrt', models.FloatField(default=0, max_length=20)),
                ('dif_average_ac', models.FloatField(default=0, max_length=20)),
                ('difaverage_sqrt', models.FloatField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_sub', models.CharField(max_length=8, null=True)),
                ('user_sub', models.CharField(max_length=8, null=True)),
                ('user_ac', models.CharField(max_length=8, null=True)),
                ('ac', models.CharField(max_length=8, null=True)),
                ('pe', models.CharField(max_length=8, null=True)),
                ('tle', models.CharField(max_length=8, null=True)),
                ('mle', models.CharField(max_length=8, null=True)),
                ('wa', models.CharField(max_length=8, null=True)),
                ('re', models.CharField(max_length=8, null=True)),
                ('ole', models.CharField(max_length=8, null=True)),
                ('ce', models.CharField(max_length=8, null=True)),
                ('se', models.CharField(max_length=8, null=True)),
                ('waiting', models.CharField(max_length=8, null=True)),
                ('fpe', models.CharField(max_length=8, null=True)),
                ('sf', models.CharField(max_length=8, null=True)),
                ('nzec', models.CharField(max_length=8, null=True)),
                ('problem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mixojapp.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='SpojProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=100)),
                ('sourceid', models.CharField(default='', max_length=20, null=True, unique=True)),
            ],
        ),
    ]
